//! Aligned buffers and the seeded bytes every input here is made from

use std::alloc::{Layout as AllocLayout, alloc_zeroed, dealloc};
use std::ops::{Deref, DerefMut};

/// The alignment every buffer here has: what direct I/O asks of a buffer the caller owns
pub const ALIGN: usize = 4096;

/// A zeroed buffer aligned for direct I/O
pub struct AlignedBuf {
    /// The start of the allocation
    ptr: *mut u8,
    /// How many bytes it holds
    len: usize,
}

impl AlignedBuf {
    /// Allocate a zeroed buffer of `len` bytes aligned to [`ALIGN`]
    ///
    /// # Arguments
    ///
    /// * `len` - How many bytes the buffer holds
    pub fn new(len: usize) -> Self {
        // a zero sized allocation is not allowed, so always ask for at least one byte
        let layout = AllocLayout::from_size_align(len.max(1), ALIGN).expect("a valid layout");
        // SAFETY: the layout has a non-zero size
        let ptr = unsafe { alloc_zeroed(layout) };
        assert!(!ptr.is_null(), "out of memory allocating {len} bytes");
        AlignedBuf { ptr, len }
    }

    /// Allocate a buffer and fill it from a seeded generator
    ///
    /// # Arguments
    ///
    /// * `len` - How many bytes the buffer holds
    /// * `seed` - The seed the bytes are generated from
    pub fn seeded(len: usize, seed: u64) -> Self {
        // allocate it zeroed first
        let mut buf = AlignedBuf::new(len);
        // then fill every byte from the generator
        SplitMix64::new(seed).fill(&mut buf);
        buf
    }
}

impl Deref for AlignedBuf {
    type Target = [u8];

    /// The buffer's bytes
    fn deref(&self) -> &[u8] {
        // SAFETY: `ptr` is a live allocation of at least `len` bytes, initialized by alloc_zeroed
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }
}

impl DerefMut for AlignedBuf {
    /// The buffer's bytes, mutably
    fn deref_mut(&mut self) -> &mut [u8] {
        // SAFETY: `ptr` is a live allocation of at least `len` bytes that only `self` points at
        unsafe { std::slice::from_raw_parts_mut(self.ptr, self.len) }
    }
}

impl Drop for AlignedBuf {
    /// Free the allocation
    fn drop(&mut self) {
        // rebuild the layout it was allocated with
        let layout = AllocLayout::from_size_align(self.len.max(1), ALIGN).expect("a valid layout");
        // SAFETY: `ptr` was allocated with exactly this layout and is freed once
        unsafe { dealloc(self.ptr, layout) }
    }
}

/// SplitMix64: the seeded generator every input here comes from, written out so that no crate's
/// release can change the bytes a check was run against
pub struct SplitMix64 {
    /// The generator's state
    state: u64,
}

impl SplitMix64 {
    /// A generator from a seed
    ///
    /// # Arguments
    ///
    /// * `seed` - The seed
    pub fn new(seed: u64) -> Self {
        SplitMix64 { state: seed }
    }

    /// The next 64 bits
    pub fn next_u64(&mut self) -> u64 {
        // advance by the golden gamma and mix, as the reference implementation does
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    /// A number below `bound`
    ///
    /// # Arguments
    ///
    /// * `bound` - One past the largest value wanted
    pub fn below(&mut self, bound: usize) -> usize {
        // the bias is irrelevant at the bounds this harness asks for
        (self.next_u64() % bound as u64) as usize
    }

    /// Fill a slice with generated bytes
    ///
    /// # Arguments
    ///
    /// * `out` - The bytes to fill
    #[allow(clippy::chunks_exact_to_as_chunks)]
    pub fn fill(&mut self, out: &mut [u8]) {
        // fill eight bytes at a time
        let mut words = out.chunks_exact_mut(8);
        for word in &mut words {
            word.copy_from_slice(&self.next_u64().to_le_bytes());
        }
        // and whatever is left from one more word
        let tail = words.into_remainder();
        let last = self.next_u64().to_le_bytes();
        tail.copy_from_slice(&last[..tail.len()]);
    }
}

/// FNV-1a over a sequence of slices: a digest whose definition is written here, used to say whether
/// two runs produced the same bytes
///
/// # Arguments
///
/// * `parts` - The slices to digest, in order
pub fn fnv1a<'a>(parts: impl IntoIterator<Item = &'a [u8]>) -> u64 {
    // the 64-bit offset basis
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for part in parts {
        for &byte in part {
            // xor the byte in, then multiply by the 64-bit prime
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    hash
}

