//! The derive that turns a struct into a projection of one of a databases tables
//!
//! A projection names a subset of a rows fields, and a get can ask to be answered with it
//! instead of with the whole row. Everything a projection needs is generated from the fields
//! it declares plus the name of the table it projects: a field the row does not have fails to
//! compile inside the conversions below, which is the check we want and needs no machinery of
//! its own.

use darling::{FromAttributes, FromField};
use quote::{format_ident, quote};
use syn::{Data, Fields, Ident};

use crate::tables::ShoalField;
use crate::traits;

/// Extend a token stream with the enum naming each tables projections
///
/// This is generated by the database macro rather than by the table derive, because a table
/// only knows its own name while the database knows every projection declared for it. The
/// whole row is always the first variant and the default, so a get that names no projection is
/// asking for the rows it always got.
///
/// # Arguments
///
/// * `stream` - The stream to extend
/// * `tables` - The row type of each table in this database
/// * `projections` - The projections each of those tables declared
pub(super) fn add_enums(
    stream: &mut proc_macro2::TokenStream,
    tables: &[Ident],
    projections: &[Vec<Ident>],
) {
    // build one enum per table naming the subsets of its rows a get can ask for
    for (table, declared) in tables.iter().zip(projections) {
        // build the name of this tables projection enum
        let enum_ident = format_ident!("{}Projection", table);
        // extend our token stream with this tables projections
        stream.extend(quote! {
            #[doc = "The subsets of a rows fields a get of this table can be answered with"]
            #[derive(
                Debug, Clone, Copy, Default, PartialEq, Eq, Hash,
                ::shoal::rkyv::Archive, ::shoal::rkyv::Serialize, ::shoal::rkyv::Deserialize,
            )]
            #[rkyv(derive(Debug))]
            pub enum #enum_ident {
                /// The whole row, which is what a get that names no projection asks for
                #[default]
                Full,
                #(
                    #[doc = "The subset of a rows fields this projection names"]
                    #declared,
                )*
            }

            #[automatically_derived]
            impl ::shoal::shared::traits::RkyvSupport for #enum_ident {}
        });
    }
}

/// Extend a token stream with a `FromShoal` implementation for every projection
///
/// A projection answers in its own response kind variant, named after the projection itself,
/// so this is the same implementation a row gets and is generated by the same code.
///
/// # Arguments
///
/// * `stream` - The stream to extend
/// * `db_ident` - The name of the database these projections belong to
/// * `projections` - The projections each of this databases tables declared
pub(super) fn add_from_shoal(
    stream: &mut proc_macro2::TokenStream,
    db_ident: &Ident,
    projections: &[Vec<Ident>],
) {
    // build the names of the types a projection is retrieved through
    let client_ident = format_ident!("{}Client", db_ident);
    let response_ident = format_ident!("Archived{}ResponseKinds", db_ident);
    // let every projection of every table be pulled back out of a response
    for projection in projections.iter().flatten() {
        traits::from_shoal::add(stream, projection, &client_ident, &response_ident);
    }
}

/// The arguments for a `ShoalProjection` derive
#[derive(Debug, FromAttributes)]
#[darling(attributes(shoal_projection))]
pub(super) struct ShoalProjectionArgs {
    /// The name of the table whose rows this projects
    pub table: String,
}

/// Build the whole implementation for a projection of one of a databases tables
///
/// # Arguments
///
/// * `ast` - The struct this derive was applied to
pub(super) fn derive(ast: &syn::DeriveInput) -> proc_macro2::TokenStream {
    // get the name of the struct we are projecting into
    let name = &ast.ident;
    // we only support structs, the same as the table derives do
    let data_struct = match &ast.data {
        Data::Struct(data_struct) => data_struct,
        _ => panic!("Only structs can be projections"),
    };
    // a projection names its fields, so it has to have named ones
    let fields = match &data_struct.fields {
        Fields::Named(fields) => &fields.named,
        _ => panic!("ShoalProjection requires named fields"),
    };
    // instance vecs for the fields this projection names and for the ones keying its partition
    let mut all_fields = Vec::default();
    let mut partition_fields = Vec::default();
    // step over our fields and pick out the ones that key this projections partition
    for field in fields {
        // parse our field attributes with the same parser the table derives use
        let field_attrs = ShoalField::from_field(field).expect("Failed to parse field attributes");
        if let Some(ident) = field_attrs.ident.clone() {
            // every field a projection names is copied out of the row it projects
            all_fields.push((ident.clone(), field_attrs.ty.clone()));
            // a sort or filter role belongs to the table, not to the subset of it we return
            if field_attrs.sort || field_attrs.filter || field_attrs.update {
                panic!(
                    "A projection field can only be marked as a partition key: {ident}"
                );
            }
            // a partition field is part of the key naming the partition this row came from
            if field_attrs.partition {
                partition_fields.push((ident.clone(), field_attrs.ty.clone()));
            }
        }
    }
    // a projection with no fields answers with nothing, which no get can want
    if all_fields.is_empty() {
        panic!("A projection has to name at least one field of its table");
    }
    // a projection has to be able to say which partition its row came from, since that is how
    // the shard collecting a split gets shares puts its rows back in the order it asked for
    if partition_fields.is_empty() {
        panic!(
            "A projection has to carry its tables partition key, so at least one of its fields \
             must be marked #[shoal(partition)]"
        );
    }
    // get the table this projection is a subset of
    let attrs = ShoalProjectionArgs::from_attributes(&ast.attrs)
        .expect("Failed to parse shoal_projection attributes");
    let table_name = Ident::new(&attrs.table, name.span());
    // build the names of the types this projection is wired into
    let archived_table = format_ident!("Archived{}", table_name);
    let projection_enum = format_ident!("{}Projection", table_name);
    // start with an empty stream
    let mut output = quote! {};
    // fold this projections shape into a constant of its own
    //
    // a projection matters to the wire because each one adds a variant to the response kinds
    // enum, and an archived enums discriminants are wire state. only a partition role is legal
    // here, so the other three role lists are empty
    let schema_fingerprint = traits::fingerprint::row_expr(
        name,
        &all_fields,
        &partition_fields,
        &[],
        &[],
        &[],
    );
    // a projection is hashed, formatted and archived exactly the way a row is
    traits::rkyv::add(&mut output, name);
    traits::partition_key::add(&mut output, name, &partition_fields);
    traits::table_row_format::add(&mut output, name, &all_fields);
    // build the field copies that turn a resident row into this projection
    let from_row_fields: Vec<_> = all_fields
        .iter()
        .map(|(ident, _)| {
            quote! {
                #ident: row.#ident.clone(),
            }
        })
        .collect();
    // build the field reads that pull this projection straight out of an archived row
    //
    // only the fields this projection named are read, which is the whole reason a projection
    // is cheaper than a get of the row it came from
    let from_archived_fields: Vec<_> = all_fields
        .iter()
        .map(|(ident, ty)| {
            quote! {
                #ident: ::shoal::rkyv::api::deserialize_using::<#ty, _, ::shoal::rkyv::rancor::Error>(
                    &row.#ident,
                    &mut pool,
                ).unwrap(),
            }
        })
        .collect();
    // generate the projection itself
    output.extend(quote! {
        #[automatically_derived]
        impl ::shoal::shared::traits::ShoalProjection for #name {
            /// The table whose rows this projects
            type Row = #table_name;

            /// A hash over this projections name, fields, types and order
            const SCHEMA_FINGERPRINT: u64 = #schema_fingerprint;

            /// Which of its tables projections this type is
            const PROJECTION: <#table_name as ::shoal::shared::traits::ShoalTableSupport>::Projection
                = #projection_enum::#name;

            /// Build this projection from a resident row
            ///
            /// # Arguments
            ///
            /// * `row` - The row to project
            fn from_row(row: &#table_name) -> Self {
                #name {
                    #(#from_row_fields)*
                }
            }

            /// Build this projection from a row still in the archive it was read from
            ///
            /// # Arguments
            ///
            /// * `row` - The archived row to project
            fn from_archived(row: &#archived_table) -> Self {
                // share one pool across this rows fields rather than building one per field
                let mut pool = ::shoal::rkyv::de::Pool::new();
                #name {
                    #(#from_archived_fields)*
                }
            }
        }

        // a projection hashes its partition key the same way its row does, so the two have to
        // agree on what that key is. this catches a projection that named the wrong fields, or
        // named them in the wrong order and so would hash to a partition nothing came from
        const _: () = {
            fn assert_partition_key<P>()
            where
                P: ::shoal::shared::traits::PartitionKeySupport<
                    PartitionKey = <#table_name as ::shoal::shared::traits::PartitionKeySupport>::PartitionKey,
                >,
            {
            }
            let _ = assert_partition_key::<#name>;
        };
    });
    output
}
