[package]
name = "shoalctl"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3"
ratatui = "0.30.0"
ratatui-hypertile = "0.2"
unicode-width = "0.2"
rkyv = "0.8"
shoal = { path = "../shoal" }
shoal-core = { path = "../shoal-core" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.11", features = ["v4"] }

# this shouldn't be required by the user
deepsize2 = "0.1"
kanal = { workspace = true }
glommio = { workspace = true }

# maybe these should?
serde = { version = "1", features = ["derive"] }


[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
