//! The set of pages the results are rendered onto, and what every one of them has in common
//!
//! # Why there is more than one page
//!
//! There used to be one. It reached 13,617 lines and 1.1 MB, of which ninety percent was
//! eighty-eight near-identical charts drawn one per workload identifier in alphabetical order. A
//! reader looking for what an insert costs found it at line 8,559, after forty-eight arms of an
//! encryption sweep. Nothing on it said how to read any of it, and two of its nine sections
//! consisted of a sentence saying the current capture had no data.
//!
//! The split is by **question**, not by workload: what a mixture costs, what width costs, what kind
//! of table costs what, what a skewed key space does, what the wire costs, what fan-out costs. Each
//! page opens with its families' four blocks - what it measures, how to read it, what would make it
//! wrong, what it cannot say - before it draws anything.
//!
//! # The set is fixed
//!
//! [`PAGES`] is a constant, not something derived from the captures. Every page needs an entry in
//! `docs/src/SUMMARY.md`, and `create-missing = false` in `book.toml` means a `SUMMARY` entry with
//! no file behind it fails the whole book build. A page that appeared because somebody added a
//! workload would break the book on the commit that added it.
//!
//! Which is also why **every page renders even when it has nothing to draw**. A capture that
//! measured no encryption still has to produce `transport.md`, saying so.

pub mod access;
pub mod all_workloads;
pub mod attribution;
pub mod configuration;
pub mod fanout;
pub mod grid;
pub mod micro;
pub mod overview;
pub mod row_size;
pub mod table_types;
pub mod transport;

use anyhow::Result;

use super::family::{self, Surface};
use super::page::Page;

/// One generated page
pub struct PageSpec {
    /// Which page this is, which carries its path and title
    pub surface: Surface,
    /// Builds its whole contents, including the heading
    pub build: fn(&Page) -> Result<String>,
}

/// Every page that is generated, in the order they are registered in `SUMMARY.md`
pub const PAGES: &[PageSpec] = &[
    PageSpec {
        surface: Surface::Overview,
        build: overview::build,
    },
    PageSpec {
        surface: Surface::Grid,
        build: grid::build,
    },
    PageSpec {
        surface: Surface::RowSize,
        build: row_size::build,
    },
    PageSpec {
        surface: Surface::TableTypes,
        build: table_types::build,
    },
    PageSpec {
        surface: Surface::Access,
        build: access::build,
    },
    PageSpec {
        surface: Surface::Transport,
        build: transport::build,
    },
    PageSpec {
        surface: Surface::Fanout,
        build: fanout::build,
    },
    PageSpec {
        surface: Surface::Configuration,
        build: configuration::build,
    },
    PageSpec {
        surface: Surface::Micro,
        build: micro::build,
    },
    PageSpec {
        surface: Surface::Attribution,
        build: attribution::build,
    },
    PageSpec {
        surface: Surface::AllWorkloads,
        build: all_workloads::build,
    },
];

/// The opening of a generated page: its heading, where it came from, and how to read it
///
/// Every page carries the same three things before any chart. The families' four blocks are the
/// reason this function exists rather than each page writing its own opening - a page that forgot
/// them would look finished.
///
/// # Arguments
///
/// * `surface` - Which page is being opened
/// * `page` - Everything the page is built from
/// * `intro` - One paragraph saying what is on this page in particular
pub fn header(surface: Surface, page: &Page, intro: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", surface.title()));
    out.push_str(
        "Generated by `shoal-bench render` from the artifacts committed under `docs/perf/`. \
         **Do not edit this page by hand** - re-run the command instead, and `shoal-bench render \
         --check` will tell you when it is out of date.\n\n",
    );
    out.push_str(intro);
    out.push_str("\n\n");
    // what the numbers below were taken against, so a reader is never holding a claim with no
    // referent. `dirty` is deliberately a boolean rather than a count, see `Page::dirty`
    //
    // the index carries the freshness table itself, so on that one page this is an anchor rather
    // than a link to the page the reader is already on
    let captured = if surface == Surface::Overview {
        "#what-has-been-captured".to_string()
    } else {
        format!("{}#what-has-been-captured", Surface::Overview.link())
    };
    out.push_str(&format!(
        "Rendered against commit `{}`{}, on `{}` with the `{}` governor. \
         [What has been captured]({captured}).\n\n",
        page.head_short,
        if page.dirty {
            " with uncommitted changes"
        } else {
            ""
        },
        page.host,
        page.governor,
    ));
    // and every family's four blocks, in declaration order
    for family in family::on(surface) {
        // a page with one family does not need its name repeated over its own contents
        if family::on(surface).len() > 1 {
            out.push_str(&format!("## {}\n\n", family.title));
        }
        out.push_str(&family.preamble());
    }
    out
}

/// Renders a caption under a chart
///
/// # Arguments
///
/// * `text` - What the caption says
pub fn caption(text: &str) -> String {
    // raw html rather than an italic line, so the stylesheet can pull it up under the chart
    format!("<span class=\"sc-caption\">{text}</span>\n\n")
}

/// What a page says when the capture it draws from measured none of its workloads
///
/// A page that renders nothing at all would be indistinguishable from a page whose generator is
/// broken, and `create-missing = false` means it cannot simply not exist.
///
/// # Arguments
///
/// * `what` - What is missing, named as the reader would name it
pub fn nothing_measured(what: &str) -> String {
    format!(
        "No capture in `docs/perf/runs/` measured {what}, so there is nothing to draw here yet. \
         Take one with `shoal-bench run --label <name>`, which captures every layer.\n\n"
    )
}

/// The closing links every page carries
///
/// # Arguments
///
/// * `surface` - The page being closed, which is left out of its own list
pub fn footer(surface: Surface) -> String {
    let mut out = String::new();
    out.push_str("## Related\n\n");
    // every sibling page, so a reader can move between questions without going back to the index
    for other in Surface::ALL {
        if other == surface {
            continue;
        }
        out.push_str(&format!("- [{}]({})\n", other.title(), other.link()));
    }
    out.push_str(
        "- [Benchmarking](benchmarking.md) - how to take a capture, and how to get a number worth \
         believing\n\
         - [Performance Baseline](baseline.md) - the frozen `B1` capture and the governor \
         experiment\n\
         - [F7, the benchmark runner](../features/bench-runner.md) - how these pages are \
         produced\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::{PAGES, caption, footer, header, nothing_measured};
    use crate::render::family::Surface;
    use crate::render::page::tests::empty_page;

    /// Every declared page has a builder, and no page is declared twice
    #[test]
    fn every_page_is_registered_exactly_once() {
        assert_eq!(PAGES.len(), Surface::ALL.len());
        for surface in Surface::ALL {
            let found = PAGES
                .iter()
                .filter(|spec| spec.surface == surface)
                .count();
            assert_eq!(found, 1, "{} is registered {found} times", surface.title());
        }
    }

    /// Every page renders from an empty tree, since the book has to build in a clean checkout
    ///
    /// `create-missing = false` means a `SUMMARY.md` entry with no file behind it fails the whole
    /// book build, so a page that declined to render when it had no data would break the book on
    /// any checkout that had not taken a capture.
    #[test]
    fn every_page_renders_with_nothing_captured() {
        let page = empty_page();
        for spec in PAGES {
            let rendered = (spec.build)(&page)
                .unwrap_or_else(|err| panic!("{} failed to render: {err:#}", spec.surface.title()));
            assert!(
                rendered.starts_with(&format!("# {}", spec.surface.title())),
                "{} does not open with its own title",
                spec.surface.title()
            );
            assert!(
                rendered.contains("## Related"),
                "{} has no way out of it",
                spec.surface.title()
            );
        }
    }

    /// Rendering a page twice produces the same bytes
    ///
    /// `render --check` compares byte for byte against the committed file, so a page that varied
    /// between two runs over the same data would fail the check on a tree nobody touched.
    #[test]
    fn every_page_renders_deterministically() {
        let page = empty_page();
        for spec in PAGES {
            let once = (spec.build)(&page).expect("it renders");
            let twice = (spec.build)(&page).expect("it renders");
            assert_eq!(once, twice, "{} is not deterministic", spec.surface.title());
        }
    }

    /// No page embeds a wall clock, or `--check` would fail every time it ran
    #[test]
    fn no_page_carries_a_wall_clock() {
        let page = empty_page();
        for spec in PAGES {
            let rendered = (spec.build)(&page).expect("it renders");
            for banned in ["generated at", "Generated at", "rendered at"] {
                assert!(
                    !rendered.contains(banned),
                    "{} embeds a wall clock via '{banned}'",
                    spec.surface.title()
                );
            }
        }
    }

    /// Every page says what it was rendered against
    #[test]
    fn every_page_names_its_commit() {
        let page = empty_page();
        for spec in PAGES {
            let rendered = (spec.build)(&page).expect("it renders");
            assert!(
                rendered.contains("commit `afd0899`"),
                "{} makes claims with no referent",
                spec.surface.title()
            );
        }
    }

    /// A page's footer links every other page but not itself
    #[test]
    fn a_footer_links_the_siblings_and_not_the_page_itself() {
        let rendered = footer(Surface::Grid);
        assert!(!rendered.contains("](grid.md)"), "a page links to itself");
        for other in Surface::ALL {
            if other != Surface::Grid {
                assert!(
                    rendered.contains(&format!("]({})", other.link())),
                    "{} is unreachable from the grid page",
                    other.title()
                );
            }
        }
    }

    /// A page with several families names each of them before its blocks
    #[test]
    fn a_page_with_two_families_names_both() {
        let rendered = header(Surface::Access, &empty_page(), "intro");
        assert!(rendered.contains("## Access patterns"));
        assert!(rendered.contains("## The load depth ladder"));
    }

    /// The index points at its own freshness table rather than at itself
    #[test]
    fn the_index_does_not_link_to_itself() {
        let rendered = header(Surface::Overview, &empty_page(), "intro");
        assert!(rendered.contains("[What has been captured](#what-has-been-captured)"));
        assert!(!rendered.contains("](overview.md"), "the index links to itself");
        // and every other page still reaches it
        let other = header(Surface::Grid, &empty_page(), "intro");
        assert!(other.contains("](overview.md#what-has-been-captured)"));
    }

    /// A page with one family does not repeat its name over its own contents
    #[test]
    fn a_page_with_one_family_does_not_repeat_itself() {
        let rendered = header(Surface::Grid, &empty_page(), "intro");
        assert!(!rendered.contains("## The workload grid"));
        assert!(rendered.contains("**What this measures.**"));
    }

    /// The two shared fragments are what they say they are
    #[test]
    fn the_shared_fragments_render() {
        assert!(caption("hello").contains("class=\"sc-caption\""));
        assert!(nothing_measured("the grid").contains("measured the grid"));
    }
}
