//! Aligned buffers, the arenas speed is measured over, and the seeded bytes that fill them

use std::alloc::{Layout as AllocLayout, alloc_zeroed, dealloc};
use std::ops::{Deref, DerefMut};

/// The alignment every buffer here has: what direct I/O asks of a buffer the caller owns
pub const ALIGN: usize = 4096;

/// A zeroed buffer aligned for direct I/O
pub struct AlignedBuf {
    /// The start of the allocation
    ptr: *mut u8,
    /// How many bytes it holds
    len: usize,
}

impl AlignedBuf {
    /// Allocate a zeroed buffer of `len` bytes aligned to [`ALIGN`]
    ///
    /// # Arguments
    ///
    /// * `len` - How many bytes the buffer holds
    pub fn new(len: usize) -> Self {
        // a zero sized allocation is not allowed, so always ask for at least one byte
        let layout = AllocLayout::from_size_align(len.max(1), ALIGN).expect("a valid layout");
        // SAFETY: the layout has a non-zero size
        let ptr = unsafe { alloc_zeroed(layout) };
        assert!(!ptr.is_null(), "out of memory allocating {len} bytes");
        AlignedBuf { ptr, len }
    }

    /// Allocate a buffer and fill it from a seeded generator
    ///
    /// # Arguments
    ///
    /// * `len` - How many bytes the buffer holds
    /// * `seed` - The seed the bytes are generated from
    pub fn seeded(len: usize, seed: u64) -> Self {
        // allocate it zeroed first
        let mut buf = AlignedBuf::new(len);
        // then fill every byte from the generator
        SplitMix64::new(seed).fill(&mut buf);
        buf
    }
}

impl Deref for AlignedBuf {
    type Target = [u8];

    /// The buffer's bytes
    fn deref(&self) -> &[u8] {
        // SAFETY: `ptr` is a live allocation of at least `len` bytes, initialized by alloc_zeroed
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }
}

impl DerefMut for AlignedBuf {
    /// The buffer's bytes, mutably
    fn deref_mut(&mut self) -> &mut [u8] {
        // SAFETY: `ptr` is a live allocation of at least `len` bytes that only `self` points at
        unsafe { std::slice::from_raw_parts_mut(self.ptr, self.len) }
    }
}

impl Drop for AlignedBuf {
    /// Free the allocation
    fn drop(&mut self) {
        // rebuild the layout it was allocated with
        let layout = AllocLayout::from_size_align(self.len.max(1), ALIGN).expect("a valid layout");
        // SAFETY: `ptr` was allocated with exactly this layout and is freed once
        unsafe { dealloc(self.ptr, layout) }
    }
}

/// SplitMix64: the seeded generator every input here comes from, written out so that no crate's
/// release can change the bytes a check was run against
pub struct SplitMix64 {
    /// The generator's state
    state: u64,
}

impl SplitMix64 {
    /// A generator from a seed
    ///
    /// # Arguments
    ///
    /// * `seed` - The seed
    pub fn new(seed: u64) -> Self {
        SplitMix64 { state: seed }
    }

    /// The next 64 bits
    pub fn next_u64(&mut self) -> u64 {
        // advance by the golden gamma and mix, as the reference implementation does
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    /// A number below `bound`
    ///
    /// # Arguments
    ///
    /// * `bound` - One past the largest value wanted
    pub fn below(&mut self, bound: usize) -> usize {
        // the bias is irrelevant at the bounds this harness asks for
        (self.next_u64() % bound as u64) as usize
    }

    /// Fill a slice with generated bytes
    ///
    /// # Arguments
    ///
    /// * `out` - The bytes to fill
    #[allow(clippy::chunks_exact_to_as_chunks)]
    pub fn fill(&mut self, out: &mut [u8]) {
        // fill eight bytes at a time
        let mut words = out.chunks_exact_mut(8);
        for word in &mut words {
            word.copy_from_slice(&self.next_u64().to_le_bytes());
        }
        // and whatever is left from one more word
        let tail = words.into_remainder();
        let last = self.next_u64().to_le_bytes();
        tail.copy_from_slice(&last[..tail.len()]);
    }
}

/// FNV-1a over a sequence of slices: a digest whose definition is written here, used to say whether
/// two runs produced the same bytes
///
/// # Arguments
///
/// * `parts` - The slices to digest, in order
pub fn fnv1a<'a>(parts: impl IntoIterator<Item = &'a [u8]>) -> u64 {
    // the 64-bit offset basis
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for part in parts {
        for &byte in part {
            // xor the byte in, then multiply by the 64-bit prime
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    hash
}

/// Round `value` up to a multiple of `to`
///
/// # Arguments
///
/// * `value` - The value to round
/// * `to` - The multiple to round to
pub fn round_up(value: usize, to: usize) -> usize {
    value.div_ceil(to) * to
}

/// One stripe's unit row held in buffers of its own, for the correctness checks
pub struct Stripe {
    /// The k data units as written
    pub data: Vec<AlignedBuf>,
    /// The chunks the code stores beside the data, or instead of it
    pub stored: Vec<AlignedBuf>,
}

impl Stripe {
    /// A stripe of seeded data units and zeroed stored chunks
    ///
    /// # Arguments
    ///
    /// * `k` - How many data units
    /// * `unit` - The size of a data unit
    /// * `stored` - How many chunks the code stores
    /// * `stored_len` - The size of a stored chunk
    /// * `seed` - The seed the data is generated from
    pub fn new(k: usize, unit: usize, stored: usize, stored_len: usize, seed: u64) -> Self {
        // one seed for each unit, so units differ from each other
        let data = (0..k)
            .map(|i| AlignedBuf::seeded(unit, seed.wrapping_add(i as u64)))
            .collect();
        // the stored chunks start zeroed and are written by an encode
        let stored = (0..stored).map(|_| AlignedBuf::new(stored_len)).collect();
        Stripe { data, stored }
    }

    /// The data units read only and the stored chunks mutably, for an encode
    pub fn encode_refs(&mut self) -> (Vec<&[u8]>, Vec<&mut [u8]>) {
        // the two halves are separate buffers, so both can be borrowed at once
        let data = self.data.iter().map(|buf| &buf[..]).collect();
        let stored = self.stored.iter_mut().map(|buf| &mut buf[..]).collect();
        (data, stored)
    }

    /// Both halves mutably, for a decode or a rebuild
    pub fn refs_mut(&mut self) -> (Vec<&mut [u8]>, Vec<&mut [u8]>) {
        // the two halves are separate buffers, so both can be borrowed at once
        let data = self.data.iter_mut().map(|buf| &mut buf[..]).collect();
        let stored = self.stored.iter_mut().map(|buf| &mut buf[..]).collect();
        (data, stored)
    }

    /// A copy of every buffer, to compare against after a decode
    pub fn snapshot(&self) -> (Vec<Vec<u8>>, Vec<Vec<u8>>) {
        // copy both halves out
        let data = self.data.iter().map(|buf| buf.to_vec()).collect();
        let stored = self.stored.iter().map(|buf| buf.to_vec()).collect();
        (data, stored)
    }
}

/// The arenas speed is measured over: large enough that no host keeps them in cache
pub struct Arenas {
    /// The data units of every row, seeded once
    pub data: AlignedBuf,
    /// The stored chunks of every row
    pub stored: AlignedBuf,
    /// The bytes an update writes, as one unit
    pub new: AlignedBuf,
}

/// How one code's rows are cut from the arenas at one layout and unit
#[derive(Clone, Copy)]
pub struct Cut {
    /// The data units a row
    pub k: usize,
    /// The size of a data unit
    pub unit: usize,
    /// The stored chunks a row
    pub count: usize,
    /// The size of a stored chunk
    pub len: usize,
    /// The distance between two stored chunks in the arena
    pub stride: usize,
    /// How many rows fit both arenas
    pub rows: usize,
}

impl Arenas {
    /// Allocate the arenas and fault every page in, so that no measurement pays for a first touch
    ///
    /// # Arguments
    ///
    /// * `data_bytes` - The size of the data arena
    /// * `stored_bytes` - The size of the stored arena
    /// * `unit_max` - The largest unit an update writes
    pub fn new(data_bytes: usize, stored_bytes: usize, unit_max: usize) -> Self {
        // the data arena is seeded, which touches every page
        let data = AlignedBuf::seeded(data_bytes, 0xda7a);
        // the stored arena is zeroed by the allocator but not touched, so write it once
        let mut stored = AlignedBuf::new(stored_bytes);
        stored.iter_mut().step_by(ALIGN).for_each(|byte| *byte = 1);
        // the update's new bytes
        let new = AlignedBuf::seeded(unit_max, 0x0e3);
        Arenas { data, stored, new }
    }

    /// Cut rows for one code at one layout and unit
    ///
    /// # Arguments
    ///
    /// * `k` - The data units a row
    /// * `unit` - The size of a data unit
    /// * `count` - The stored chunks a row
    /// * `len` - The size of a stored chunk
    pub fn cut(&self, k: usize, unit: usize, count: usize, len: usize) -> Cut {
        // a stored chunk that is a whole number of pages keeps its alignment; one that is not is
        // still kept on a cache line
        let stride = if len.is_multiple_of(ALIGN) {
            len
        } else {
            round_up(len, 64)
        };
        // as many rows as both arenas hold, and never fewer than one
        let by_data = self.data.len() / (k * unit);
        let by_stored = self.stored.len() / (count * stride).max(1);
        let rows = by_data.min(by_stored).max(1);
        Cut {
            k,
            unit,
            count,
            len,
            stride,
            rows,
        }
    }
}

impl Cut {
    /// One row's data units and stored chunks, both mutably
    ///
    /// # Arguments
    ///
    /// * `data` - The data arena
    /// * `stored` - The stored arena
    /// * `row` - Which row
    pub fn row<'a>(
        &self,
        data: &'a mut [u8],
        stored: &'a mut [u8],
        row: usize,
    ) -> (Vec<&'a mut [u8]>, Vec<&'a mut [u8]>) {
        // the row's data units are contiguous in the data arena
        let data_start = row * self.k * self.unit;
        let data = data[data_start..data_start + self.k * self.unit]
            .chunks_mut(self.unit)
            .collect();
        // and its stored chunks are contiguous in the stored arena, each cut down to its length
        let stored_start = row * self.count * self.stride;
        let len = self.len;
        let stored = stored[stored_start..stored_start + self.count * self.stride]
            .chunks_mut(self.stride)
            .map(|chunk| &mut chunk[..len])
            .collect();
        (data, stored)
    }
}
